// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projur.Data.DBConfiguration.EFCore;

namespace Projur.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projur.Data.Models.Escolaridade", b =>
                {
                    b.Property<int>("EscolaridadeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<string>("Descricao");

                    b.Property<DateTime>("DtCriacao");

                    b.Property<DateTime?>("DtUltAlteracao");

                    b.HasKey("EscolaridadeId");

                    b.ToTable("Escolaridades");
                });

            modelBuilder.Entity("Projur.Data.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<DateTime>("DtCriacao");

                    b.Property<DateTime>("DtNascimento");

                    b.Property<DateTime?>("DtUltAlteracao");

                    b.Property<string>("Email");

                    b.Property<int>("EscolaridadeId");

                    b.Property<string>("Nome");

                    b.Property<string>("Sobrenome");

                    b.HasKey("UsuarioId");

                    b.HasIndex("EscolaridadeId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Projur.Data.Models.Usuario", b =>
                {
                    b.HasOne("Projur.Data.Models.Escolaridade", "Escolaridade")
                        .WithMany()
                        .HasForeignKey("EscolaridadeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
